
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:33"
    allow:
      - dependency-name: "@carbon"
      - dependency-name: "carbon"
