name: Deploy website to IBM Cloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x

      - name: Install packages
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Build site
        run: yarn build:prefix

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh

      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install

      - name: Login
        env:
          API_KEY: ${{ secrets.IBM_CLOUD_KEY }}
        run: |
          ibmcloud login -a https://cloud.ibm.com --no-region --apikey $API_KEY \
          && ibmcloud target -o IBMDesignOrg -s idl

      - name: Deploy to US
        run: |
          ibmcloud cf v3-zdt-push design-language-website-carbon -b \
          https://github.com/cloudfoundry/nginx-buildpack.git

      - name: Deploy to EU
        run: |
          ibmcloud cf v3-zdt-push design-language-website-carbon-eu -b \
          https://github.com/cloudfoundry/nginx-buildpack.git
