name: Deploy IDL website to US IBM Cloud

on: 
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Install and build
      run: |
        yarn install
        yarn build
    - name: Install ibmcloud cli
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
    - name: Login to ibmcloud
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: ibmcloud login -a "https://api.ng.bluemix.net" -u apikey -p "$API_KEY" -o "IBMDesignOrg" -s "idl"  
    - name: Install ibmcloud plugins
      run: |
        ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
        ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community
    - name: Deploy website
      run: |
        ibmcloud cf blue-green-deploy design-language-new -f manifest.production.yml --delete-old-apps
